import axios from 'axios'

export async function generateResponse(prompt: string, providerId: string): Promise<string> {
  const apiKey = process.env.OPENROUTER_API_KEY

  if (apiKey) {
    // Map providerId to actual OpenRouter model identifiers
    const models: Record<string, string> = {
      'cheap-llm': 'meta-llama/llama-3.2-1b-instruct:free',
      'balanced-ai': 'meta-llama/llama-3.1-8b-instruct:free',
      'premium-ai': 'google/gemini-2-flash',
    }

    const modelName = models[providerId] || 'meta-llama/llama-3.1-8b-instruct:free'

    try {
      const response = await axios.post(
        'https://openrouter.ai/api/v1/chat/completions',
        {
          model: modelName,
          messages: [{ role: 'user', content: prompt }],
        },
        {
          headers: {
            Authorization: `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
          },
          timeout: 10000,
        }
      )
      
      const content = response.data?.choices?.[0]?.message?.content
      if (content) {
        return `[Real routed output from ${providerId} (${modelName})]\n\n${content}`
      }
    } catch (e: any) {
      console.warn(`Real API call failed for ${providerId}, falling back to mock:`, e.message || e)
    }
  }

  // Simulate processing delay based on provider
  const delays: Record<string, number> = {
    'cheap-llm': 280,
    'premium-ai': 180,
    'balanced-ai': 220,
  }

  const delay = delays[providerId] || 200
  await new Promise(resolve => setTimeout(resolve, delay))

  // Generate mock response
  const responses: Record<string, string> = {
    'cheap-llm': `[Budget AI Response]\n\n${prompt}\n\nThis is a cost-effective response optimized for simple queries. Response generated by Budget AI (${providerId}).`,
    'premium-ai': `[Premium AI Response]\n\n${prompt}\n\nThis is a high-quality, detailed response with advanced reasoning capabilities. Powered by Premium AI (${providerId}).`,
    'balanced-ai': `[Balanced AI Response]\n\n${prompt}\n\nThis response balances quality and cost, suitable for most use cases. Generated by Balanced AI (${providerId}).`,
  }

  return responses[providerId] || `Response to: ${prompt}`
}

export async function callProvider(providerId: string, prompt: string): Promise<{ result: string; latency: number }> {
  const startTime = Date.now()

  try {
    const result = await generateResponse(prompt, providerId)
    const latency = Date.now() - startTime

    return { result, latency }
  } catch (error) {
    throw new Error(`Provider ${providerId} failed: ${error}`)
  }
}
